# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli
  displayName: 'Install Dependencies'

- script: npm install
  displayName: 'Install'

- script: npx ng build --prod
  displayName: 'Build'

- script: npx ng test --watch=false
  displayName: 'Tests'  
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '$(Build.ArtifactStagingDirectory)/**/*.xml'
  displayName: 'Publish Test Results'  